### ISSUE TITLE
Missing non-anon mode and deletion link

### ISSUE THREAD

**Issue by salty-horse** [atbaker/imgur-uploader#1]
The tool is useful, but it would be even better if you could opt into uploading an image in non-anonymous mode, so it would be linked to your account, and you'd have a way of deleting it.

In anonymous mode, the tool should print out the deletion link.

**Comment by atbaker** [comment]
@salty-horse Thanks for the issue! I enjoyed writing this little tool, but I don't intend to maintain it.

It's MIT Licensed though, so feel free to fork it and do whatever you see fit!
