### ISSUE TITLE
Add credentials into the profile.

### ISSUE THREAD

**Issue by skorokithakis** [atbaker/imgur-uploader#2]
Would you accept a PR that allows storing the credentials in a file in the user's ~/.config dir? I know that you don't intend to maintain it, but we can't fork the PyPI name :( I'd be happy to maintain it for you, though, if you want.

**Comment by atbaker** [comment]
Hey @skorokithakis!

It looks like PyPI stopped recording download stats earlier this year, but I just checked and was surprised to see so many downloads for this library: http://pypi-ranking.info/module/imgur-uploader

If you're up for the job of maintaining it, I'll happily give you full control and make you an owner on PyPI.

I can also make you a full collaborator on this repo, or you can fork it and update PyPI to point to your repo.

How does that sound?

**Comment by skorokithakis** [comment]
Either way sounds good to me, I've forked it because I wanted to add the credentials, so whichever way works for you is fine by me.

Thanks!

**Comment by atbaker** [comment]
Alright - you're an Owner on PyPI and I just updated the README on this repo with a big notice pointing to your fork.

Let me know if there's anything else you need from me. And of course, thanks for taking stewardship of the project.

**Comment by skorokithakis** [comment]
Thank you!
